CREATE TABLE containers (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    port INTEGER,
    cpu_limit INTEGER NOT NULL DEFAULT 500,
    memory_limit INTEGER NOT NULL DEFAULT 512,
    environment_vars JSONB,
    deployment_type VARCHAR(20),
    source_url TEXT,
    build_status VARCHAR(20),
    build_logs TEXT,
    container_id VARCHAR(255),
    localhost_url VARCHAR(500),
    public_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    started_at TIMESTAMP WITH TIME ZONE,
    stopped_at TIMESTAMP WITH TIME ZONE
);
