"""baseline existing schema

Revision ID: 83c62c5555bc
Revises: 
Create Date: 2026-01-14 05:59:52.231945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83c62c5555bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.alter_column('containers', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'running', 'stopped', 'error', name='containerstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('containers', 'environment_vars',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('containers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('containers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_index(op.f('ix_containers_user_id'), 'containers', ['user_id'], unique=False)
    op.drop_constraint(op.f('containers_parent_id_fkey'), 'containers', type_='foreignkey')
    op.create_foreign_key(None, 'containers', 'users', ['user_id'], ['id'])
    op.drop_column('containers', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.create_foreign_key(op.f('containers_parent_id_fkey'), 'containers', 'containers', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_containers_user_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.alter_column('containers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('containers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('containers', 'environment_vars',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('containers', 'status',
               existing_type=sa.Enum('pending', 'running', 'stopped', 'error', name='containerstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table('user_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('verify', 'reset', name='tokentype'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_tokens_pkey')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_tokens_token_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###
